name: flutter_doctor_nearby
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  hidable: ^1.0.6
  readmore: ^3.0.0
  date_picker_timeline: ^1.2.6
  easy_date_timeline: ^1.1.3
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf