// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbREPm2JOC6WjeL7veFfkIqfeC_XV86vU',
    appId: '1:891880355648:android:d0cbebc223354f4665eca5',
    messagingSenderId: '891880355648',
    projectId: 'doctornearby-95dea',
    databaseURL: 'https://doctornearby-95dea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctornearby-95dea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjF0_8_rXXoW04aCJl7lQsbz8lpHBrBH4',
    appId: '1:891880355648:ios:b03a0e660bbadf2165eca5',
    messagingSenderId: '891880355648',
    projectId: 'doctornearby-95dea',
    databaseURL: 'https://doctornearby-95dea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctornearby-95dea.appspot.com',
    iosBundleId: 'com.example.flutterDoctorNearby',
  );
}
